name: Sync README to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  push-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Push README to Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: kellenmurphy/py-conf-sync
          readme-filepath: ./README.md
